# -*- coding: utf-8 -*-
"""preprocess_un.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QUAAmB990J4qvLFaPNoHFM3YtRoeAObk

*Preprocessing part for Unsupervised Learning project of GaIB.*

Libraries
"""

import pandas as pd

"""# Reading the Data"""


def read_dataset(csv):
    dataset = pd.read_csv(csv)
    return dataset


"""# Clean and Convert the Dataset to Numpy Array"""


def get_clean_dataset(csv):
    # Read the dataset
    dataset = read_dataset(csv)

    # Remove the first column of ID
    dataset.drop(dataset.columns[0], axis=1, inplace=True)

    # Map the categorical value for better processing
    # Gender Mappings
    gender_map = {"Male": 0, "Female": 1}
    dataset.replace({"Gender": gender_map}, inplace=True)

    return dataset.to_numpy()


# Additional preprocessing for KMeans
def preprocess_num(csv):
    clean_dataset = get_clean_dataset(csv)

    return clean_dataset[:, 1:]


# dataset = get_clean_dataset("/content/dataset.csv")
# dataset
